name: Tests

on:
  push:
    branches: [ DEN-169_workflow ]
  pull_request:
    branches: [ DEN-169_workflow]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...
